services:
  - type: web
    name: pickleball-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_8SYnbg9IHNDA@ep-tiny-star-a9jxbgn7-pooler.gwc.azure.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://pickle-ball-g6clrugyf-aryan-shahs-projects-8276b85a.vercel.app
    healthCheckPath: /api/v1/health
    autoDeploy: true 