services:
  - type: web
    name: pickleball-backend
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      npx prisma generate
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://pickle-ball-g6clrugyf-aryan-shahs-projects-8276b85a.vercel.app
    healthCheckPath: /api/v1/health
    autoDeploy: true 